### PR TITLE
Feature/create profile

### PR DESCRIPTION
**Pull request by j-ferber**
I think I finished the create profile functionality. Can somebody check it to see if it works for them? I used zod for error checking on inputs, but it is not necessary as it can be done manually as well.

### CODE REVIEW

**Comment by Victor-M-Giraldo** [comment]
Also, I think it might not be a bad idea to put the zod schemas in the models folder. We would just have one folder for the mongoose schemas and another one for the zod ones.

Eventually, having an actual error page instead of just sending json errors is probably a good idea as well.

Other than that thought, it looks good to me and I tested it out and it looks like signup works.

**Comment by snehabanda30** [comment]
Yeah, I just tested it as well. It worked would it be possible, if we could merge the request into the main. Would we need to put the zod schemas in the models folder?

**Comment by j-ferber** [comment]
We do not need to move the zod schemas into the model folder for it to work, it can be done later if you guys want to move it. We also do not have to use zod, I just did not want to do the input error handling myself. I was keeping the models separate because they are related to mongoose for MongoDB and I was just gonna put all schemas inside the schema.js file (User and Post) so we can import them for error handling later if we were to use them. Also, I sent JSON errors so that they can be rendered on the page without sending them to a separate page to show errors. When you signup for a website, it usually tells you the errors in your username, password, etc. on the page and not by sending to a different page so I felt a separate error page was unnecessary. Again, it can always be changed later as we have a decent amount of time.

**Comment by Victor-M-Giraldo** [comment]
> We do not need to move the zod schemas into the model folder for it to work, it can be done later if you guys want to move it. We also do not have to use zod, I just did not want to do the input error handling myself. I was keeping the models separate because they are related to mongoose for MongoDB and I was just gonna put all schemas inside the schema.js file (User and Post) so we can import them for error handling later if we were to use them. Also, I sent JSON errors so that they can be rendered on the page without sending them to a separate page to show errors. When you signup for a website, it usually tells you the errors in your username, password, etc. on the page and not by sending to a different page so I felt a separate error page was unnecessary. Again, it can always be changed later as we have a decent amount of time.

Ah, got it.

**Pull request merged**
